%% Analisi proprietà Biciclo
clear all
syms x_M y_M theta_A theta_P
x = [x_M; y_M; theta_A; theta_P];
fprintf('lo stato iniziale considerato è \n:')
x0 = [0; 0; 0; 0];
Lm = 0.2;
L = 3;
phi = theta_A-theta_P;
fprintf('il sistema è dato da:')
f = [0;...
	 0;...
	 0;...
	 0];
g1 = [cos(phi)*cos(theta_P)-(Lm/L)*sin(phi)*sin(theta_P);...
	  cos(phi)*sin(theta_P)+(Lm/L)*sin(phi)*cos(theta_P);...
									0					;...
							(1/L)*sin(phi)					];
g2 = [ 0;...
	   0;...
	   1;...
	   0];

G = [g1 g2];
y1 = x_M
y2 = y_M
y = [y1;y2];
[r_mimo,Lf_full_mimo, T, E] = relative_degree_mimo(f,G,y,x)
%% integratore sulla velocità
fprintf('Sistema con integratore a monte sulla velocità :')
syms v
x = [x ; v]
f = [g1*v;...
	   0]
g1 = [0;...
	  0;...
	  0;...
	  0;...
	  1];
g2 = [ 0;...
	   0;...
	   1;...
	   0;...
	   0]; 
G = [g1 g2];
[r_mimo,Lf_full_mimo, T, E] = relative_degree_mimo(f,G,y,x) 
% fprintf('Sistema con integratore a monte sulla velocità :')
% %%integratore theta e velocità
% clearvars -except x f g1 g2 y
% syms omega
% x = [x ; omega]
% f = [f+g2*omega;...
% 		0]
% g1 = [g1;...
% 	   0]
% g2 = [0;...
% 	  0;...
% 	  0;...
% 	  0;...
% 	  0;...
% 	  1]
% G = [g1 g2];
% [r_mimo,Lf_full_mimo, T, E] = relative_degree_mimo(f,G,y,x)

%% doppio integratore velocità commentare il blocco precedente
clearvars -except x f g1 g2 y
syms v_dot
x = [x ; v_dot]
f = [f+g1*v_dot;...
	 0];
g1 = [0;...
	  0;...
	  0;...
	  0;...
	  0;...
	  1];
g2 = [ 0;...
	   0;...
	   1;...
	   0;...
	   0;...
	   0];
G = [g1 g2];
[r_mimo,Lf_full_mimo, T, E] = relative_degree_mimo(f,G,y,x)
