%% Script description
% This script computes and plots angle between the subspace generated by the
% selected rPCs and the one generated by the mean_posture PCs.


% posture computed as the mean of each rPC among all subjects.
% It requires the choice of ngroup.


% How we obtained mean_posture PCs? Follow the steps:
% 1.	Mean at each time step between all selected trial for each subject 
%		(njoints x nsample) for each subject.
% 2.	For each subject, we compute the "temporal" mean for each joint 
%		angle. We get a (njoints x 1) for each subject. We lose this way
%		the temporal information
% (3.)	We stack each subject to his own group (h, la, a)
% 3.	We stack together all subjects
% 4.	autovettori = PCA(njoints x subjects)^T
%% intro
clear all; clc;

ngroup = 1;		
%		- ngroup: number between 1, 2 and 3. it selects which group of task
%		we want to analyze. (1 = int, 2 = tr, 3 = tm, 'all' = all tasks)
% load data

flag_mean = 0;
% if flag_mean = 0 mean posture is computed as PCA of mean postures of each
% subject
% if flag_mean = 1 mean posture is computed as MEAN of mean postures of each
% subject

data_rPCA_all = rpca_all_subj(ngroup);
mean_posture = mean_post(ngroup, flag_mean);

%% selected subject e rPCs
nsubj = 8;		% selected subject

%% parameters load
nsamples = size(data_rPCA_all(1).h.mean,2);

%% extrapulate angles one at a time

sel_rPC = [1 2 3];
[angles, dom] = rPC_angle(data_rPCA_all, nsubj, sel_rPC, mean_posture);
if dom == -1
	rPCsangles_h	= angles;
	angle_norm		= vecnorm(rPCsangles_h, 2, 1);
else
	rPCsangles_s	= angles(:,:,1);
	angle_norm_s	= vecnorm(rPCsangles_s, 2, 1);
	rPCsangles_la	= angles(:,:,2);
	angle_norm_la	= vecnorm(rPCsangles_la, 2, 1);
end

%% plot

%legend msg
legend_msg = [];
for i = 1:length(sel_rPC)
	msg_tmp = ['principal angle ' num2str(i)];
	legend_msg = cat(1, legend_msg, msg_tmp);
end

if dom == -1
	figure(1)
	clf
	plot(rPCsangles_h')
	hold on
	plot(angle_norm','k--')
	grid on
	title(['Subspace angles of Healthy subj ' num2str(nsubj) ' between span rPCs and span mean PCs'])
	legend(legend_msg)
	xlim([1 size(rPCsangles_h,2)])
	ylim([0 max(angle_norm)+3])
	xlabel('Time samples')
	ylabel('Angle [deg]')
else
	figure(1)
	clf
	plot(rPCsangles_s')
	hold on
	plot(angle_norm_s','k--')
	grid on	
	if dom
		title(['Subspace angles of A_d subj ' num2str(nsubj) ' between span rPCs and span mean PCs'])
		legend(legend_msg)	
	else
		title(['Subspace angles of A_{nd} subj ' num2str(nsubj) 'between span rPCs and span mean PCs'])
		legend(legend_msg)
	end
	xlim([1 size(rPCsangles_s,2)])
	ylim([0 max(angle_norm_s)+3])
	
	figure(2)
	clf
	plot(rPCsangles_la')
	hold on
	plot(angle_norm_la','k--')
	grid on	
	if dom
		title(['Subspace angles of LA_d subj ' num2str(nsubj) 'between span rPCs and span mean PCs'])
		legend(legend_msg)
	else
		title(['Subspace angles of LA_{nd} subj ' num2str(nsubj) 'between span rPCs and span mean PCs'])
		legend(legend_msg)
	end
	xlim([1 size(rPCsangles_la,2)])
	ylim([0 max(angle_norm_la)+3])
	xlabel('Time samples')
	ylabel('Angle [deg]')
end