f = [ x_t_dot;...
		  0;...
		  y_t_dot;...
		  0;...
		  theta_dot;...
		  -2*(L_dot/L)*theta_dot+0.5*phi_dot^2*sin(2*theta)-(g/L)*sin(theta)- b_smorza * theta_dot;...
		  phi_dot;...
		  -2*(L_dot/L)*phi_dot-2*phi_dot*theta_dot*cot(theta);...
		  L_dot;...
		  0]
	  
	% accelerazione del carrello lungo l'asse x
	fprintf('in: accelerazione carrello lungo asse x \n')  
	g1 = [0;...
		  1;...
		  0;...
		  0;...
		  0;...
		  -cos(theta)*sin(phi)/L;...
		  0;...
		  -cos(phi)/(sin(theta)*L);...
		  0;...
		  0]
	% accelerazione del carrello lungo l'asse y
	fprintf('in: accelerazione carrello lungo asse y \n')  	  
	g2 = [0;...
		  0;...
		  0;...
		  1;...
		  0;...
		  -cos(theta)*cos(phi)/L;...
		  0;...
		  sin(phi)/(sin(theta)*L);...
		  0;...
		  0]
	% accelerazione dell'allungamento dell'asta
	fprintf('in: accelerazione dell''allungamento dell''asta \n')  	  
	g3 = [0;...
		  0;...
		  0;...
		  0;...
		  0;...
		  0;...
		  0;...
		  0;...
		  0;...
		  1]
	  
	  
	  %%%
+int( ,t,0,t)	  
x_T = [	x_t0+int(x_t_dot0+int(x_t_ddot,t,0,t) ,t,0,t);...
		x_t_dot0+int(x_t_ddot,t,0,t);...
		y_t0+int(y_t_dot0 + int(y_t_ddot ,t,0,t) ,t,0,t);...
		y_t_dot0+int(y_t_ddot ,t,0,t);...
		theta0+int((exp(-(t*(2*L_dot + L*b_smorza))/L)*(L*theta_dot_0 - int(exp((x*(2*L_dot + L*b_smorza))/L)*(- L*cos(theta(x))*sin(theta(x))*phi_dot^2 + g*sin(theta(x)) + cos(theta(x))*cos(phi)*y_t_ddot(x) + cos(theta(x))*sin(phi)*x_t_ddot(x)), x, 0, t, 'IgnoreSpecialCases', true)))/L,t,0,t);...
		(exp(-(t*(2*L_dot + L*b_smorza))/L)*(L*theta_dot_0 - int(exp((x*(2*L_dot + L*b_smorza))/L)*(- L*cos(theta(x))*sin(theta(x))*phi_dot^2 + g*sin(theta(x)) + cos(theta(x))*cos(phi)*y_t_ddot(x) + cos(theta(x))*sin(phi)*x_t_ddot(x)), x, 0, t, 'IgnoreSpecialCases', true)))/L
		phi0+int((exp(-(2*t*(L_dot + L*theta_dot*cot(theta)))/L)*(L*phi_dot_0*sin(theta) - int(exp((2*x*(L_dot + L*theta_dot*cot(theta)))/L)*(cos(phi(x))*x_t_ddot(x) - sin(phi(x))*y_t_ddot(x)), x, 0, t, 'IgnoreSpecialCases', true)))/(L*sin(theta)),t,0,t);...
		(exp(-(2*t*(L_dot + L*theta_dot*cot(theta)))/L)*(L*phi_dot_0*sin(theta) - int(exp((2*x*(L_dot + L*theta_dot*cot(theta)))/L)*(cos(phi(x))*x_t_ddot(x) - sin(phi(x))*y_t_ddot(x)), x, 0, t, 'IgnoreSpecialCases', true)))/(L*sin(theta));...
		L0 + int(L_dot0 +int(L_ddot,t,0,t) ,t,0,t);...
		L_dot0 +int(L_ddot,t,0,t)]