% confronto pendolo
syms x1 x2 x3 x4 real
l = 2; % lunghezza pendolo
m = 1;
M = 19;
fprintf('il sistema del pendolo è dato da')
f = [x3;...
	 x4;...
	 m*(l*sin(x2)*x4^2-m*g*sin(x2)*cos(x2))/(M+m*sin(x2));...
	 (M+m)*g*sin(x2) - m*l*cos(x2)*sin(x2)*x4^2/(l*(M+m*sin(x2)))]
g = [0;...
	 0;...
	 1/(M+m*sin(x2));...
	 -cos(x2)/(l*(M+m*sin(x2)))]
 y = x2
