function armplot(q, arm, trial)
q_plot = q'./180*pi;

figure(2)
arm.plot(q_plot,...
		'workspace', plot_lims(trial, 0.5),...
		'fps', 60,...
		'raise',...
		'ortho',...
		'view', [25 10],...
		'noname',...
		'scale', 0.5,...
		'jointdiam',1);

end