function lims = plot_lims(trial, lim_gap, flag)

if nargin < 2
	lim_gap = 0.2;
end
if nargin < 3
	flag = 0;
end

if flag == 1
	xmin = min([ ...
		min(trial.L5.Pos(:,1)), ...
		min(trial.Upperarm_R.Pos(:,1)),...
		min(trial.Upperarm_L.Pos(:,1)),...
		min(trial.Forearm_R.Pos(:,1)),...
		min(trial.Forearm_L.Pos(:,1)),...
		min(trial.Hand_R.Pos(:,1)),...
		min(trial.Hand_L.Pos(:,1)),...
		min(trial.Toe_R.Pos(:,1)), ...
		min(trial.Foot_R.Pos(:,1)),...
		min(trial.Toe_L.Pos(:,1)),...
		min(trial.Foot_L.Pos(:,1)),...
		]) - lim_gap;
	xmax = max([ ...
		max(trial.L5.Pos(:,1)), ...
		max(trial.Upperarm_R.Pos(:,1)),...
		max(trial.Upperarm_L.Pos(:,1)),...
		max(trial.Forearm_R.Pos(:,1)),...
		max(trial.Forearm_L.Pos(:,1)),...
		max(trial.Hand_R.Pos(:,1)),...
		max(trial.Hand_L.Pos(:,1)),...
		max(trial.Toe_R.Pos(:,1)), ...
		max(trial.Foot_R.Pos(:,1)),...
		max(trial.Toe_L.Pos(:,1)),...
		max(trial.Foot_L.Pos(:,1)),...
		]) + lim_gap;
	ymin = min([ ...
		min(trial.L5.Pos(:,2)), ...
		min(trial.Upperarm_R.Pos(:,2)),...
		min(trial.Upperarm_L.Pos(:,2)),...
		min(trial.Forearm_R.Pos(:,2)),...
		min(trial.Forearm_L.Pos(:,2)),...
		min(trial.Hand_R.Pos(:,2)),...
		min(trial.Hand_L.Pos(:,2)),...
		min(trial.Toe_R.Pos(:,2)), ...
		min(trial.Foot_R.Pos(:,2)),...
		min(trial.Toe_L.Pos(:,2)),...
		min(trial.Foot_L.Pos(:,2)),...
		]) - lim_gap;
	ymax = max([ ...
		max(trial.L5.Pos(:,2)), ...
		max(trial.Upperarm_R.Pos(:,2)),...
		max(trial.Upperarm_L.Pos(:,2)),...
		max(trial.Forearm_R.Pos(:,2)),...
		max(trial.Forearm_L.Pos(:,2)),...
		max(trial.Hand_R.Pos(:,2)),...
		max(trial.Hand_L.Pos(:,2)),...
		max(trial.Toe_R.Pos(:,2)), ...
		max(trial.Foot_R.Pos(:,2)),...
		max(trial.Toe_L.Pos(:,2)),...
		max(trial.Foot_L.Pos(:,2)),...
		]) + lim_gap;
	zmin = 0;
	zmax = max([ ...
		max(trial.L5.Pos(:,3)), ...
		max(trial.Upperarm_R.Pos(:,3)),...
		max(trial.Upperarm_L.Pos(:,3)),...
		max(trial.Forearm_R.Pos(:,3)),...
		max(trial.Forearm_L.Pos(:,3)),...
		max(trial.Hand_R.Pos(:,3)),...
		max(trial.Hand_L.Pos(:,3)),...
		max(trial.Toe_R.Pos(:,3)), ...
		max(trial.Foot_R.Pos(:,3)),...
		max(trial.Toe_L.Pos(:,3)),...
		max(trial.Foot_L.Pos(:,3)),...
		]) + lim_gap;
	
	else
	xmin = min([ ...
		min(trial.L5.Pos(:,1)), ...
		min(trial.Upperarm_R.Pos(:,1)),...
		min(trial.Upperarm_L.Pos(:,1)),...
		min(trial.Forearm_R.Pos(:,1)),...
		min(trial.Forearm_L.Pos(:,1)),...
		min(trial.Hand_R.Pos(:,1)),...
		min(trial.Hand_L.Pos(:,1)),...
		]) - lim_gap;
	xmax = max([ ...
		max(trial.L5.Pos(:,1)), ...
		max(trial.Upperarm_R.Pos(:,1)),...
		max(trial.Upperarm_L.Pos(:,1)),...
		max(trial.Forearm_R.Pos(:,1)),...
		max(trial.Forearm_L.Pos(:,1)),...
		max(trial.Hand_R.Pos(:,1)),...
		max(trial.Hand_L.Pos(:,1)),...
		]) + lim_gap;
	ymin = min([ ...
		min(trial.L5.Pos(:,2)), ...
		min(trial.Upperarm_R.Pos(:,2)),...
		min(trial.Upperarm_L.Pos(:,2)),...
		min(trial.Forearm_R.Pos(:,2)),...
		min(trial.Forearm_L.Pos(:,2)),...
		min(trial.Hand_R.Pos(:,2)),...
		min(trial.Hand_L.Pos(:,2)),...
		]) - lim_gap;
	ymax = max([ ...
		max(trial.L5.Pos(:,2)), ...
		max(trial.Upperarm_R.Pos(:,2)),...
		max(trial.Upperarm_L.Pos(:,2)),...
		max(trial.Forearm_R.Pos(:,2)),...
		max(trial.Forearm_L.Pos(:,2)),...
		max(trial.Hand_R.Pos(:,2)),...
		max(trial.Hand_L.Pos(:,2)),...
		]) + lim_gap;
	zmin = 0;
	zmax = max([ ...
		max(trial.L5.Pos(:,3)), ...
		max(trial.Upperarm_R.Pos(:,3)),...
		max(trial.Upperarm_L.Pos(:,3)),...
		max(trial.Forearm_R.Pos(:,3)),...
		max(trial.Forearm_L.Pos(:,3)),...
		max(trial.Hand_R.Pos(:,3)),...
		max(trial.Hand_L.Pos(:,3)),...
		]) + lim_gap;
end

lims = [xmin xmax ymin ymax zmin zmax];
	

end