clear all
syms x_M y_M phi theta_P L
x = [x_M; y_M; phi; theta_P];
fprintf('lo stato iniziale considerato è \n:')
x0 = [0; 0; 0; 0];
Lm = 0;
% L = 3;
fprintf('il sistema è dato da:')
f = [0;...
	 0;...
	 0;...
	 0];
g1 = [cos(phi)*cos(theta_P);...
	  cos(phi)*sin(theta_P);...
			0	  ;...
	 (1/L)*sin(phi)]
g2 = [ 0;...
	   0;...
	   1;...
	   0]
G = [g1 g2];
y1 = x_M
y2 = y_M
y = [y1;y2];
[r_mimo,Lf_full_mimo, T, E] = relative_degree_mimo(f,G,y,x)
fprintf('il rango di E è :\n')
rank(E)
%%
fprintf('Sistema con integratore a monte sulla velocità :\n')
syms v_P
x = [x ; v_P]
f = [g1*v_P;...
	   0]
g1 = [0;...
	  0;...
	  0;...
	  0;...
	  1]
g2 = [ 0;...
	   0;...
	   1;...
	   0;...
	   0]
G = [g1 g2];
[r_mimo,Lf_full_mimo, T, E] = relative_degree_mimo(f,G,y,x) 
fprintf('il rango di E è :\n')
rank(E)
%%
clearvars -except x f g1 g2 y
syms v_P_dot
x = [x ; v_P_dot]
f = [f+g1*v_P_dot;...
	 0]
g1 = [0;...
	  0;...
	  0;...
	  0;...
	  0;...
	  1]
g2 = [ 0;...
	   0;...
	   1;...
	   0;...
	   0;...
	   0]
G = [g1 g2];
[r_mimo,Lf_full_mimo, T, E] = relative_degree_mimo(f,G,y,x)
clearvars -except T E