function animation(task)
% animation
% example: animation(strokes_data.task1.subject1.right_side.trial1)
% this function runs the animation of the selected task, it requires
% strokes_data.mat or healthy_data.mat to run.

% NON SERVE DATO CHE PER LANCIARLO SERVE AVERE NEL WORKSPACE LA STRUCT
% ALTRIMENTI NON GLI PASSA NIENTE, COMODO PER ALTRE VOLTE PERO`
% if ~exist('healthy_data', 'var') || (exist('healthy_data', 'var') && ~isstruct(healthy_data) )
% 	clear healthy_data;
% 	load('healthy_data.mat');
% elseif  ~exist('strokes_data', 'var') || (exist('strokes_data', 'var') && ~isstruct(strokes_data) )
% 	clear strokes_data;
% 	load('strokes_data.mat');
% end

%% Constant definition
animate = task;		% stores into a local variable the selected task structure
stroke_side = task.stroke_side;
skip_frame = 2;		% how many frame it skips every update
nSamples = size(animate.P_Head,1);

% colours
col_head = 'ko';	% colour head and neck
col_head_in = 'k';	% colour inside of the head and neck
col_h = 'go';		% colour healthy arm
col_h_in = 'g';		% colour inside healthy arm
col_s = 'ro';		% colour stroke arm
col_s_in = 'r';		% colour stroke arm inside
col_segm = 'k-';	% colour segment

% check if right / left arm is healthy or not
% upper limb with strokes 0-->Left 1--> Right, -1-->Both arm healthy
if stroke_side == -1
	col_r = col_h;			% colour right arm
	col_r_in = col_h_in;	% colour inside right arm
	col_l = col_h;			% colour left arm
	col_l_in = col_h_in;	% colour left arm inside
elseif stroke_side == 0
	col_r = col_h;			% colour right arm
	col_r_in = col_h_in;	% colour inside right arm
	col_l = col_s;			% colour stroke - left arm 
	col_l_in = col_s_in;	% colour inside stroke - left arm 
elseif stroke_side == 1
	col_r = col_s;			% colour stroke - right arm
	col_r_in = col_s_in;	% colour inside stroke - right arm
	col_l = col_h;			% colour left arm
	col_l_in = col_h_in;	% colour left arm inside
else
	error('stroke_side not found!')
end

% marker dimensions
dim_small = 10;		% small marker dimension (shoulder, neck, elbow)
dim_big = 15;		% big marker dimension (hands, head)

% limits for plot
lim_gap = 0.2;
xmin = min([ ...
	min(animate.P_Head(:,1)), ...
	min(animate.P_Neck(:,1)),...
	min(animate.P_Shoulder_R(:,1)),...
	min(animate.P_Shoulder_L(:,1)),...
	min(animate.P_Upperarm_R(:,1)),...
	min(animate.P_Upperarm_L(:,1)),...
	min(animate.P_Forearm_R(:,1)),...
	min(animate.P_Forearm_L(:,1)),...
	min(animate.P_Hand_R(:,1)),...
	min(animate.P_Hand_L(:,1)),...
	]) - lim_gap;
xmax = max([ ...
	max(animate.P_Head(:,1)), ...
	max(animate.P_Neck(:,1)),...
	max(animate.P_Shoulder_R(:,1)),...
	max(animate.P_Shoulder_L(:,1)),...
	max(animate.P_Upperarm_R(:,1)),...
	max(animate.P_Upperarm_L(:,1)),...
	max(animate.P_Forearm_R(:,1)),...
	max(animate.P_Forearm_L(:,1)),...
	max(animate.P_Hand_R(:,1)),...
	max(animate.P_Hand_L(:,1)),...
	]) + lim_gap;
ymin = min([ ...
	min(animate.P_Head(:,2)), ...
	min(animate.P_Neck(:,2)),...
	min(animate.P_Shoulder_R(:,2)),...
	min(animate.P_Shoulder_L(:,2)),...
	min(animate.P_Upperarm_R(:,2)),...
	min(animate.P_Upperarm_L(:,2)),...
	min(animate.P_Forearm_R(:,2)),...
	min(animate.P_Forearm_L(:,2)),...
	min(animate.P_Hand_R(:,2)),...
	min(animate.P_Hand_L(:,2)),...
	]) - lim_gap;
ymax = max([ ...
	max(animate.P_Head(:,2)), ...
	max(animate.P_Neck(:,2)),...
	max(animate.P_Shoulder_R(:,2)),...
	max(animate.P_Shoulder_L(:,2)),...
	max(animate.P_Upperarm_R(:,2)),...
	max(animate.P_Upperarm_L(:,2)),...
	max(animate.P_Forearm_R(:,2)),...
	max(animate.P_Forearm_L(:,2)),...
	max(animate.P_Hand_R(:,2)),...
	max(animate.P_Hand_L(:,2)),...
	]) + lim_gap;
zmin = 0;
zmax = max([ ...
	max(animate.P_Head(:,3)), ...
	max(animate.P_Neck(:,3)),...
	max(animate.P_Shoulder_R(:,3)),...
	max(animate.P_Shoulder_L(:,3)),...
	max(animate.P_Upperarm_R(:,3)),...
	max(animate.P_Upperarm_L(:,3)),...
	max(animate.P_Forearm_R(:,3)),...
	max(animate.P_Forearm_L(:,3)),...
	max(animate.P_Hand_R(:,3)),...
	max(animate.P_Hand_L(:,3)),...
	]) + lim_gap;

%% Animation
for i=1:skip_frame:(nSamples)
    
	%% head
	plot3(animate.P_Head(i,1),...
        animate.P_Head(i,2),...
        animate.P_Head(i,3),...
        col_head,'MarkerSize', dim_big,'MarkerFaceColor',col_head_in)
    grid on
    hold on
    
    % head - neck
    plot3([animate.P_Head(i,1); animate.P_Neck(i,1)],...
        [animate.P_Head(i,2); animate.P_Neck(i,2)],...
        [animate.P_Head(i,3); animate.P_Neck(i,3)],...
         col_segm)
    
    % neck
    plot3(animate.P_Neck(i,1),...
        animate.P_Neck(i,2),...
        animate.P_Neck(i,3),...
        col_head,'MarkerSize', dim_small,'MarkerFaceColor',col_head_in)
    
	%% right arm
    % neck - right shoulder
    plot3([animate.P_Neck(i,1); animate.P_Shoulder_R(i,1)],...
        [animate.P_Neck(i,2); animate.P_Shoulder_R(i,2)],...
        [animate.P_Neck(i,3); animate.P_Shoulder_R(i,3)],...
         col_segm)
    
    % right shoulder
    plot3(animate.P_Shoulder_R(i,1),...
        animate.P_Shoulder_R(i,2),...
        animate.P_Shoulder_R(i,3),...
         col_r,'MarkerSize', dim_small,'MarkerFaceColor', col_r_in)
    
    % right shoulder - right upper arm
     plot3([animate.P_Shoulder_R(i,1); animate.P_Upperarm_R(i,1)],...
        [animate.P_Shoulder_R(i,2); animate.P_Upperarm_R(i,2)],...
        [animate.P_Shoulder_R(i,3); animate.P_Upperarm_R(i,3)],...
         col_segm)
    
    % right upper arm
    plot3(animate.P_Upperarm_R(i,1),...
        animate.P_Upperarm_R(i,2),...
        animate.P_Upperarm_R(i,3),...
         col_r,'MarkerSize', dim_small,'MarkerFaceColor', col_r_in)
    
    % right upper arm - right forearm
    plot3([animate.P_Upperarm_R(i,1); animate.P_Forearm_R(i,1)],...
        [animate.P_Upperarm_R(i,2); animate.P_Forearm_R(i,2)],...
        [animate.P_Upperarm_R(i,3); animate.P_Forearm_R(i,3)],...
         col_segm)
	 
    % right forearm
    plot3(animate.P_Forearm_R(i,1),...
        animate.P_Forearm_R(i,2),...
        animate.P_Forearm_R(i,3),...
         col_r,'MarkerSize', dim_small,'MarkerFaceColor', col_r_in)
    
    % right forearm - right hand
	plot3([animate.P_Forearm_R(i,1); animate.P_Hand_R(i,1)],...
        [animate.P_Forearm_R(i,2); animate.P_Hand_R(i,2)],...
        [animate.P_Forearm_R(i,3); animate.P_Hand_R(i,3)],...
         col_segm)
	
    % right hand
    plot3(animate.P_Hand_R(i,1),...
        animate.P_Hand_R(i,2),...
        animate.P_Hand_R(i,3),...
         col_r,'MarkerSize', dim_big,'MarkerFaceColor', col_r_in)

	%% braccio sinistro
	% neck - left shoulder
    plot3([animate.P_Neck(i,1); animate.P_Shoulder_L(i,1)],...
        [animate.P_Neck(i,2); animate.P_Shoulder_L(i,2)],...
        [animate.P_Neck(i,3); animate.P_Shoulder_L(i,3)],...
         col_segm)
    
    % left shoulder
    plot3(animate.P_Shoulder_L(i,1),...
        animate.P_Shoulder_L(i,2),...
        animate.P_Shoulder_L(i,3),...
         col_l,'MarkerSize', dim_small,'MarkerFaceColor', col_l_in)
    
    % left shoulder - left upper arm
     plot3([animate.P_Shoulder_L(i,1); animate.P_Upperarm_L(i,1)],...
        [animate.P_Shoulder_L(i,2); animate.P_Upperarm_L(i,2)],...
        [animate.P_Shoulder_L(i,3); animate.P_Upperarm_L(i,3)],...
         col_segm)
    
    % left upper arm
    plot3(animate.P_Upperarm_L(i,1),...
        animate.P_Upperarm_L(i,2),...
        animate.P_Upperarm_L(i,3),...
         col_l,'MarkerSize', dim_small,'MarkerFaceColor', col_l_in)
    
    % left upper arm - left forearm
    plot3([animate.P_Upperarm_L(i,1); animate.P_Forearm_L(i,1)],...
        [animate.P_Upperarm_L(i,2); animate.P_Forearm_L(i,2)],...
        [animate.P_Upperarm_L(i,3); animate.P_Forearm_L(i,3)],...
         col_segm)
	 
    % left forearm
    plot3(animate.P_Forearm_L(i,1),...
        animate.P_Forearm_L(i,2),...
        animate.P_Forearm_L(i,3),...
         col_l,'MarkerSize', dim_small,'MarkerFaceColor', col_l_in)
    
    % left forearm - left hand
	plot3([animate.P_Forearm_L(i,1); animate.P_Hand_L(i,1)],...
        [animate.P_Forearm_L(i,2); animate.P_Hand_L(i,2)],...
        [animate.P_Forearm_L(i,3); animate.P_Hand_L(i,3)],...
         col_segm)
	
    % left hand
    plot3(animate.P_Hand_L(i,1),...
        animate.P_Hand_L(i,2),...
        animate.P_Hand_L(i,3),...
         col_l,'MarkerSize', dim_big,'MarkerFaceColor', col_l_in)

    %% option plot
    xlabel('x');    ylabel('y');    zlabel('z');
    axis equal
	
    xlim([xmin, xmax]);  ylim([ymin, ymax]); zlim([zmin, zmax]);
    hold off 
	%view([25 10 45])
    drawnow()
    
    hold off
	
end



